# Shell script (sh)

name="toybox"
version="0.8.1 Development [2019.05.29]"

if [ -d "/system/system" ]; then
	system="system/system"
	vendor="vendor"
else
	system="system"
	vendor="vendor"
fi

# 0.8.1 Development [2019.05.29] / 200 Apples [ARM 64]

chown 0.2000 "/$system/bin/toybox-dev"
chmod 0755 "/$system/bin/toybox-dev"

ln -s "toybox-dev" "/$system/bin/acpi"
ln -s "toybox-dev" "/$system/bin/ascii"
ln -s "toybox-dev" "/$system/bin/base64"
ln -s "toybox-dev" "/$system/bin/basename"
# ln -s "toybox-dev" "/$system/bin/blkid" # bin-blkid
ln -s "toybox-dev" "/$system/bin/blockdev"
# ln -s "toybox-dev" "/$system/bin/bunzip2" # bin-bzip2
# ln -s "toybox-dev" "/$system/bin/bzcat" # bin-bzip2
ln -s "toybox-dev" "/$system/bin/cal"
ln -s "toybox-dev" "/$system/bin/cat"
ln -s "toybox-dev" "/$system/bin/catv"
ln -s "toybox-dev" "/$system/bin/chattr"
ln -s "toybox-dev" "/$system/bin/chgrp"
ln -s "toybox-dev" "/$system/bin/chmod"
ln -s "toybox-dev" "/$system/bin/chown"
ln -s "toybox-dev" "/$system/bin/chroot"
ln -s "toybox-dev" "/$system/bin/chrt"
ln -s "toybox-dev" "/$system/bin/chvt"
ln -s "toybox-dev" "/$system/bin/cksum"
ln -s "toybox-dev" "/$system/bin/clear"
ln -s "toybox-dev" "/$system/bin/cmp"
ln -s "toybox-dev" "/$system/bin/comm"
ln -s "toybox-dev" "/$system/bin/count"
ln -s "toybox-dev" "/$system/bin/cp"
ln -s "toybox-dev" "/$system/bin/cpio"
ln -s "toybox-dev" "/$system/bin/crc32"
ln -s "toybox-dev" "/$system/bin/cut"
ln -s "toybox-dev" "/$system/bin/date"
ln -s "toybox-dev" "/$system/bin/devmem"
ln -s "toybox-dev" "/$system/bin/df"
ln -s "toybox-dev" "/$system/bin/dirname"
ln -s "toybox-dev" "/$system/bin/dmesg"
ln -s "toybox-dev" "/$system/bin/dos2unix"
ln -s "toybox-dev" "/$system/bin/du"
ln -s "toybox-dev" "/$system/bin/echo"
# ln -s "toybox-dev" "/$system/bin/egrep" # bin-grep
ln -s "toybox-dev" "/$system/bin/eject"
ln -s "toybox-dev" "/$system/bin/env"
ln -s "toybox-dev" "/$system/bin/expand"
ln -s "toybox-dev" "/$system/bin/factor"
ln -s "toybox-dev" "/$system/bin/fallocate"
ln -s "toybox-dev" "/$system/bin/false"
# ln -s "toybox-dev" "/$system/bin/fgrep" # bin-grep
ln -s "toybox-dev" "/$system/bin/file"
ln -s "toybox-dev" "/$system/bin/find"
ln -s "toybox-dev" "/$system/bin/flock"
ln -s "toybox-dev" "/$system/bin/fmt"
ln -s "toybox-dev" "/$system/bin/free"
ln -s "toybox-dev" "/$system/bin/freeramdisk"
ln -s "toybox-dev" "/$system/bin/fsfreeze"
ln -s "toybox-dev" "/$system/bin/fstype"
ln -s "toybox-dev" "/$system/bin/fsync"
ln -s "toybox-dev" "/$system/bin/ftpget"
ln -s "toybox-dev" "/$system/bin/ftpput"
ln -s "toybox-dev" "/$system/bin/getconf"
# ln -s "toybox-dev" "/$system/bin/grep" # bin-grep
ln -s "toybox-dev" "/$system/bin/groups"
ln -s "toybox-dev" "/$system/bin/gunzip"
ln -s "toybox-dev" "/$system/bin/halt"
ln -s "toybox-dev" "/$system/bin/head"
# ln -s "toybox-dev" "/$system/bin/help" # hide command
ln -s "toybox-dev" "/$system/bin/hexedit"
ln -s "toybox-dev" "/$system/bin/hostname"
ln -s "toybox-dev" "/$system/bin/hwclock"
ln -s "toybox-dev" "/$system/bin/i2cdetect"
ln -s "toybox-dev" "/$system/bin/i2cdump"
ln -s "toybox-dev" "/$system/bin/i2cget"
ln -s "toybox-dev" "/$system/bin/i2cset"
ln -s "toybox-dev" "/$system/bin/iconv"
ln -s "toybox-dev" "/$system/bin/id"
ln -s "toybox-dev" "/$system/bin/ifconfig"
ln -s "toybox-dev" "/$system/bin/inotifyd"
ln -s "toybox-dev" "/$system/bin/insmod"
ln -s "toybox-dev" "/$system/bin/install"
ln -s "toybox-dev" "/$system/bin/ionice"
ln -s "toybox-dev" "/$system/bin/iorenice"
ln -s "toybox-dev" "/$system/bin/iotop" # bin-iotop
ln -s "toybox-dev" "/$system/bin/kill"
ln -s "toybox-dev" "/$system/bin/killall"
ln -s "toybox-dev" "/$system/bin/killall5"
ln -s "toybox-dev" "/$system/bin/link"
ln -s "toybox-dev" "/$system/bin/ln"
ln -s "toybox-dev" "/$system/bin/logger"
ln -s "toybox-dev" "/$system/bin/login"
ln -s "toybox-dev" "/$system/bin/logname"
ln -s "toybox-dev" "/$system/bin/losetup"
ln -s "toybox-dev" "/$system/bin/ls"
ln -s "toybox-dev" "/$system/bin/lsattr"
ln -s "toybox-dev" "/$system/bin/lsmod"
ln -s "toybox-dev" "/$system/bin/lspci"
ln -s "toybox-dev" "/$system/bin/lsusb"
ln -s "toybox-dev" "/$system/bin/makedevs"
ln -s "toybox-dev" "/$system/bin/mcookie"
ln -s "toybox-dev" "/$system/bin/md5sum"
ln -s "toybox-dev" "/$system/bin/microcom"
ln -s "toybox-dev" "/$system/bin/mix"
ln -s "toybox-dev" "/$system/bin/mkdir"
ln -s "toybox-dev" "/$system/bin/mkfifo"
ln -s "toybox-dev" "/$system/bin/mknod"
ln -s "toybox-dev" "/$system/bin/mkpasswd"
ln -s "toybox-dev" "/$system/bin/mkswap"
ln -s "toybox-dev" "/$system/bin/mktemp"
ln -s "toybox-dev" "/$system/bin/modinfo"
ln -s "toybox-dev" "/$system/bin/mount"
ln -s "toybox-dev" "/$system/bin/mountpoint"
ln -s "toybox-dev" "/$system/bin/mv"
ln -s "toybox-dev" "/$system/bin/nbd-client"
ln -s "toybox-dev" "/$system/bin/nc"
ln -s "toybox-dev" "/$system/bin/netcat"
ln -s "toybox-dev" "/$system/bin/netstat"
ln -s "toybox-dev" "/$system/bin/nice"
ln -s "toybox-dev" "/$system/bin/nl"
ln -s "toybox-dev" "/$system/bin/nohup"
ln -s "toybox-dev" "/$system/bin/nproc"
ln -s "toybox-dev" "/$system/bin/od"
ln -s "toybox-dev" "/$system/bin/oneit"
ln -s "toybox-dev" "/$system/bin/partprobe"
ln -s "toybox-dev" "/$system/bin/passwd"
ln -s "toybox-dev" "/$system/bin/paste"
ln -s "toybox-dev" "/$system/bin/patch"
ln -s "toybox-dev" "/$system/bin/pgrep"
ln -s "toybox-dev" "/$system/bin/pidof"
# ln -s "toybox-dev" "/$system/bin/ping" # bin-ping
# ln -s "toybox-dev" "/$system/bin/ping6" # bin-ping6
ln -s "toybox-dev" "/$system/bin/pivot_root"
ln -s "toybox-dev" "/$system/bin/pkill"
ln -s "toybox-dev" "/$system/bin/pmap"
ln -s "toybox-dev" "/$system/bin/poweroff"
ln -s "toybox-dev" "/$system/bin/printenv"
ln -s "toybox-dev" "/$system/bin/printf"
ln -s "toybox-dev" "/$system/bin/prlimit"
ln -s "toybox-dev" "/$system/bin/ps"
ln -s "toybox-dev" "/$system/bin/pwd"
ln -s "toybox-dev" "/$system/bin/pwdx"
ln -s "toybox-dev" "/$system/bin/readahead"
ln -s "toybox-dev" "/$system/bin/readlink"
ln -s "toybox-dev" "/$system/bin/realpath"
# ln -s "toybox-dev" "/$system/bin/reboot" # bin-reboot
ln -s "toybox-dev" "/$system/bin/renice"
ln -s "toybox-dev" "/$system/bin/reset" # xbin-tset
ln -s "toybox-dev" "/$system/bin/rev"
ln -s "toybox-dev" "/$system/bin/rfkill"
ln -s "toybox-dev" "/$system/bin/rm"
ln -s "toybox-dev" "/$system/bin/rmdir"
ln -s "toybox-dev" "/$system/bin/rmmod"
ln -s "toybox-dev" "/$system/bin/sed"
ln -s "toybox-dev" "/$system/bin/seq"
ln -s "toybox-dev" "/$system/bin/setfattr"
ln -s "toybox-dev" "/$system/bin/setsid"
ln -s "toybox-dev" "/$system/bin/sha1sum"
ln -s "toybox-dev" "/$system/bin/shred"
ln -s "toybox-dev" "/$system/bin/sleep"
ln -s "toybox-dev" "/$system/bin/sntp"
ln -s "toybox-dev" "/$system/bin/sort"
ln -s "toybox-dev" "/$system/bin/split"
ln -s "toybox-dev" "/$system/bin/stat" # bin-stat
ln -s "toybox-dev" "/$system/bin/strings" # bin-strings
# ln -s "toybox-dev" "/$system/bin/su" # hide command
ln -s "toybox-dev" "/$system/bin/swapoff"
ln -s "toybox-dev" "/$system/bin/swapon"
ln -s "toybox-dev" "/$system/bin/switch_root"
ln -s "toybox-dev" "/$system/bin/sync"
ln -s "toybox-dev" "/$system/bin/sysctl"
ln -s "toybox-dev" "/$system/bin/tac"
ln -s "toybox-dev" "/$system/bin/tail"
ln -s "toybox-dev" "/$system/bin/tar"
ln -s "toybox-dev" "/$system/bin/taskset"
ln -s "toybox-dev" "/$system/bin/tee"
ln -s "toybox-dev" "/$system/bin/test"
ln -s "toybox-dev" "/$system/bin/time"
ln -s "toybox-dev" "/$system/bin/timeout"
ln -s "toybox-dev" "/$system/bin/top"
ln -s "toybox-dev" "/$system/bin/touch"
ln -s "toybox-dev" "/$system/bin/true"
ln -s "toybox-dev" "/$system/bin/truncate"
ln -s "toybox-dev" "/$system/bin/tty"
ln -s "toybox-dev" "/$system/bin/tunctl"
ln -s "toybox-dev" "/$system/bin/ulimit"
ln -s "toybox-dev" "/$system/bin/umount"
ln -s "toybox-dev" "/$system/bin/uname"
ln -s "toybox-dev" "/$system/bin/uniq"
ln -s "toybox-dev" "/$system/bin/unix2dos"
ln -s "toybox-dev" "/$system/bin/unlink"
ln -s "toybox-dev" "/$system/bin/uptime"
ln -s "toybox-dev" "/$system/bin/usleep"
ln -s "toybox-dev" "/$system/bin/uudecode"
ln -s "toybox-dev" "/$system/bin/uuencode"
ln -s "toybox-dev" "/$system/bin/uuidgen"
ln -s "toybox-dev" "/$system/bin/vconfig"
ln -s "toybox-dev" "/$system/bin/vmstat"
ln -s "toybox-dev" "/$system/bin/w"
ln -s "toybox-dev" "/$system/bin/watch"
ln -s "toybox-dev" "/$system/bin/wc"
ln -s "toybox-dev" "/$system/bin/which"
ln -s "toybox-dev" "/$system/bin/who"
ln -s "toybox-dev" "/$system/bin/whoami"
ln -s "toybox-dev" "/$system/bin/xargs"
ln -s "toybox-dev" "/$system/bin/xxd"
ln -s "toybox-dev" "/$system/bin/yes"
ln -s "toybox-dev" "/$system/bin/zcat"
