### BOROVETS SCRIPT

## BUILD

. "$(cd $(dirname ${0}); pwd)/borovets/system/bin/borovets-functions"

## SCRIPT

# echo "$script_folder/$script_name ${@}"

echo "Запуск сценария"
echo " "
sleep 0.5
echo "Установка модулей и расширений"

sleep 0.5

name="toybox"
version="0.8.0 Android"

echo " - $name $version"

# 0.8.0 Android / 196 Applets [ARM 64]

chown 0.2000 "/$system/bin/toybox"
chmod 0755 "/$system/bin/toybox"

ln -s "toybox" "/$system/bin/acpi"
ln -s "toybox" "/$system/bin/base64"
ln -s "toybox" "/$system/bin/basename"
ln -s "toybox" "/$system/bin/bc" # bin-bc
# ln -s "toybox" "/$system/bin/blkid" # bin-blkid
ln -s "toybox" "/$system/bin/blockdev"
ln -s "toybox" "/$system/bin/cal"
ln -s "toybox" "/$system/bin/cat"
ln -s "toybox" "/$system/bin/chattr"
ln -s "toybox" "/$system/bin/chcon"
ln -s "toybox" "/$system/bin/chgrp"
ln -s "toybox" "/$system/bin/chmod"
ln -s "toybox" "/$system/bin/chown"
ln -s "toybox" "/$system/bin/chroot"
ln -s "toybox" "/$system/bin/chrt"
ln -s "toybox" "/$system/bin/cksum"
ln -s "toybox" "/$system/bin/clear"
ln -s "toybox" "/$system/bin/cmp"
ln -s "toybox" "/$system/bin/comm"
ln -s "toybox" "/$system/bin/cp"
ln -s "toybox" "/$system/bin/cpio"
ln -s "toybox" "/$system/bin/cut"
ln -s "toybox" "/$system/bin/date"
# ln -s "toybox" "/$system/bin/dd" # bin-toolbox
ln -s "toybox" "/$system/bin/devmem"
ln -s "toybox" "/$system/bin/df"
ln -s "toybox" "/$system/bin/diff"
ln -s "toybox" "/$system/bin/dirname"
ln -s "toybox" "/$system/bin/dmesg"
ln -s "toybox" "/$system/bin/dos2unix"
ln -s "toybox" "/$system/bin/du"
ln -s "toybox" "/$system/bin/echo"
# ln -s "toybox" "/$system/bin/egrep" # bin-grep
ln -s "toybox" "/$system/bin/env"
ln -s "toybox" "/$system/bin/expand"
ln -s "toybox" "/$system/bin/expr"
ln -s "toybox" "/$system/bin/fallocate"
ln -s "toybox" "/$system/bin/false"
# ln -s "toybox" "/$system/bin/fgrep" # bin-grep
ln -s "toybox" "/$system/bin/file"
ln -s "toybox" "/$system/bin/find"
ln -s "toybox" "/$system/bin/flock"
ln -s "toybox" "/$system/bin/fmt"
ln -s "toybox" "/$system/bin/free"
ln -s "toybox" "/$system/bin/freeramdisk"
ln -s "toybox" "/$system/bin/fsfreeze"
ln -s "toybox" "/$system/bin/fsync"
ln -s "toybox" "/$system/bin/getconf"
ln -s "toybox" "/$system/bin/getenforce"
ln -s "toybox" "/$system/bin/getfattr"
# ln -s "toybox" "/$system/bin/grep" # bin-grep
ln -s "toybox" "/$system/bin/groups"
ln -s "toybox" "/$system/bin/gunzip" # bin-pigz / xbin-busybox
ln -s "toybox" "/$system/bin/gzip" # bin-pigz / xbin-busybox
ln -s "toybox" "/$system/bin/head"
ln -s "toybox" "/$system/bin/help"
ln -s "toybox" "/$system/bin/hostname"
ln -s "toybox" "/$system/bin/hwclock"
ln -s "toybox" "/$system/bin/i2cdetect" # bin-i2cdetect
ln -s "toybox" "/$system/bin/i2cdump" # bin-i2cdump
ln -s "toybox" "/$system/bin/i2cget" # bin-i2cget
ln -s "toybox" "/$system/bin/i2cset" # bin-i2cset
ln -s "toybox" "/$system/bin/iconv"
ln -s "toybox" "/$system/bin/id"
ln -s "toybox" "/$system/bin/ifconfig"
ln -s "toybox" "/$system/bin/inotifyd"
ln -s "toybox" "/$system/bin/insmod"
ln -s "toybox" "/$system/bin/install"
ln -s "toybox" "/$system/bin/ionice"
ln -s "toybox" "/$system/bin/iorenice"
ln -s "toybox" "/$system/bin/iotop" # bin-iotop
ln -s "toybox" "/$system/bin/kill"
ln -s "toybox" "/$system/bin/killall"
ln -s "toybox" "/$system/bin/ln"
ln -s "toybox" "/$system/bin/load_policy"
ln -s "toybox" "/$system/bin/log"
ln -s "toybox" "/$system/bin/logname"
ln -s "toybox" "/$system/bin/losetup"
ln -s "toybox" "/$system/bin/ls"
ln -s "toybox" "/$system/bin/lsattr"
ln -s "toybox" "/$system/bin/lsmod"
ln -s "toybox" "/$system/bin/lsof"
ln -s "toybox" "/$system/bin/lspci"
ln -s "toybox" "/$system/bin/lsusb"
ln -s "toybox" "/$system/bin/makedevs"
ln -s "toybox" "/$system/bin/md5sum"
ln -s "toybox" "/$system/bin/microcom"
ln -s "toybox" "/$system/bin/mkdir"
ln -s "toybox" "/$system/bin/mkfifo"
ln -s "toybox" "/$system/bin/mknod"
ln -s "toybox" "/$system/bin/mkswap"
ln -s "toybox" "/$system/bin/mktemp"
ln -s "toybox" "/$system/bin/modinfo"
ln -s "toybox" "/$system/bin/modprobe"
ln -s "toybox" "/$system/bin/more"
ln -s "toybox" "/$system/bin/mount"
ln -s "toybox" "/$system/bin/mountpoint"
ln -s "toybox" "/$system/bin/mv"
ln -s "toybox" "/$system/bin/nbd-client"
ln -s "toybox" "/$system/bin/nc"
ln -s "toybox" "/$system/bin/netcat"
ln -s "toybox" "/$system/bin/netstat"
ln -s "toybox" "/$system/bin/nice"
ln -s "toybox" "/$system/bin/nl"
ln -s "toybox" "/$system/bin/nohup"
ln -s "toybox" "/$system/bin/nproc"
ln -s "toybox" "/$system/bin/nsenter"
ln -s "toybox" "/$system/bin/od"
ln -s "toybox" "/$system/bin/partprobe"
ln -s "toybox" "/$system/bin/paste"
ln -s "toybox" "/$system/bin/patch"
ln -s "toybox" "/$system/bin/pgrep"
ln -s "toybox" "/$system/bin/pidof"
ln -s "toybox" "/$system/bin/ping" # bin-ping
ln -s "toybox" "/$system/bin/ping6" # bin-ping6
ln -s "toybox" "/$system/bin/pivot_root"
ln -s "toybox" "/$system/bin/pkill"
ln -s "toybox" "/$system/bin/pmap"
ln -s "toybox" "/$system/bin/printenv"
ln -s "toybox" "/$system/bin/printf"
ln -s "toybox" "/$system/bin/prlimit"
ln -s "toybox" "/$system/bin/ps"
ln -s "toybox" "/$system/bin/pwd"
ln -s "toybox" "/$system/bin/pwdx"
ln -s "toybox" "/$system/bin/readlink"
ln -s "toybox" "/$system/bin/realpath"
ln -s "toybox" "/$system/bin/renice"
ln -s "toybox" "/$system/bin/restorecon"
ln -s "toybox" "/$system/bin/rev"
ln -s "toybox" "/$system/bin/rfkill"
ln -s "toybox" "/$system/bin/rm"
ln -s "toybox" "/$system/bin/rmdir"
ln -s "toybox" "/$system/bin/rmmod"
ln -s "toybox" "/$system/bin/runcon"
ln -s "toybox" "/$system/bin/sed"
ln -s "toybox" "/$system/bin/sendevent"
ln -s "toybox" "/$system/bin/seq"
ln -s "toybox" "/$system/bin/setenforce"
ln -s "toybox" "/$system/bin/setfattr"
ln -s "toybox" "/$system/bin/setprop"
ln -s "toybox" "/$system/bin/setsid"
ln -s "toybox" "/$system/bin/sha1sum"
ln -s "toybox" "/$system/bin/sha224sum"
ln -s "toybox" "/$system/bin/sha256sum"
ln -s "toybox" "/$system/bin/sha384sum"
ln -s "toybox" "/$system/bin/sha512sum"
ln -s "toybox" "/$system/bin/sleep"
ln -s "toybox" "/$system/bin/sort"
ln -s "toybox" "/$system/bin/split"
ln -s "toybox" "/$system/bin/start"
ln -s "toybox" "/$system/bin/stat" # bin-stat
ln -s "toybox" "/$system/bin/stop"
ln -s "toybox" "/$system/bin/strings" # bin-strings
ln -s "toybox" "/$system/bin/stty"
ln -s "toybox" "/$system/bin/swapoff"
ln -s "toybox" "/$system/bin/swapon"
ln -s "toybox" "/$system/bin/sync"
ln -s "toybox" "/$system/bin/sysctl"
ln -s "toybox" "/$system/bin/tac"
ln -s "toybox" "/$system/bin/tail"
ln -s "toybox" "/$system/bin/tar"
ln -s "toybox" "/$system/bin/taskset"
ln -s "toybox" "/$system/bin/tee"
ln -s "toybox" "/$system/bin/time"
ln -s "toybox" "/$system/bin/timeout"
ln -s "toybox" "/$system/bin/top"
ln -s "toybox" "/$system/bin/touch"
ln -s "toybox" "/$system/bin/tr"
ln -s "toybox" "/$system/bin/traceroute" # bin-traceroute
ln -s "toybox" "/$system/bin/traceroute6" # bin-traceroute6
ln -s "toybox" "/$system/bin/true"
ln -s "toybox" "/$system/bin/truncate"
ln -s "toybox" "/$system/bin/tty"
ln -s "toybox" "/$system/bin/tunctl"
ln -s "toybox" "/$system/bin/ulimit"
ln -s "toybox" "/$system/bin/umount"
ln -s "toybox" "/$system/bin/uname"
ln -s "toybox" "/$system/bin/uniq"
ln -s "toybox" "/$system/bin/unix2dos"
ln -s "toybox" "/$system/bin/unlink"
ln -s "toybox" "/$system/bin/unshare"
ln -s "toybox" "/$system/bin/uptime"
ln -s "toybox" "/$system/bin/usleep"
ln -s "toybox" "/$system/bin/uudecode"
ln -s "toybox" "/$system/bin/uuencode"
ln -s "toybox" "/$system/bin/uuidgen"
ln -s "toybox" "/$system/bin/vconfig"
ln -s "toybox" "/$system/bin/vmstat"
ln -s "toybox" "/$system/bin/watch"
ln -s "toybox" "/$system/bin/wc"
ln -s "toybox" "/$system/bin/which"
ln -s "toybox" "/$system/bin/whoami"
ln -s "toybox" "/$system/bin/xargs"
ln -s "toybox" "/$system/bin/xxd"
ln -s "toybox" "/$system/bin/yes"
ln -s "toybox" "/$system/bin/zcat" # bin-pigz / xbin-busybox

chcon -h u:object_r:toolbox_exec:s0 "/$system/bin/toybox"

sleep 0.2

name="toybox_vendor"
version="0.7.6 Android"

echo " - $name $version"

# 0.7.6 Android / 178 Applets [ARM 64]

chown 0.2000 "/$vendor/bin/toybox_vendor"
chmod 0755 "/$vendor/bin/toybox_vendor"

ln -s "toybox_vendor" "/$vendor/bin/acpi"
ln -s "toybox_vendor" "/$vendor/bin/base64"
ln -s "toybox_vendor" "/$vendor/bin/basename"
# ln -s "toybox_vendor" "/$vendor/bin/blkid" # bug comman
ln -s "toybox_vendor" "/$vendor/bin/blockdev"
ln -s "toybox_vendor" "/$vendor/bin/cal"
ln -s "toybox_vendor" "/$vendor/bin/cat"
ln -s "toybox_vendor" "/$vendor/bin/chattr"
ln -s "toybox_vendor" "/$vendor/bin/chcon"
ln -s "toybox_vendor" "/$vendor/bin/chgrp"
ln -s "toybox_vendor" "/$vendor/bin/chmod"
ln -s "toybox_vendor" "/$vendor/bin/chown"
ln -s "toybox_vendor" "/$vendor/bin/chroot"
ln -s "toybox_vendor" "/$vendor/bin/chrt"
ln -s "toybox_vendor" "/$vendor/bin/cksum"
ln -s "toybox_vendor" "/$vendor/bin/clear"
ln -s "toybox_vendor" "/$vendor/bin/cmp"
ln -s "toybox_vendor" "/$vendor/bin/comm"
ln -s "toybox_vendor" "/$vendor/bin/cp"
ln -s "toybox_vendor" "/$vendor/bin/cpio"
ln -s "toybox_vendor" "/$vendor/bin/cut"
ln -s "toybox_vendor" "/$vendor/bin/date"
# ln -s "toybox_vendor" "/$vendor/bin/dd" # bin-toolbox
ln -s "toybox_vendor" "/$vendor/bin/df"
ln -s "toybox_vendor" "/$vendor/bin/diff"
ln -s "toybox_vendor" "/$vendor/bin/dirname"
ln -s "toybox_vendor" "/$vendor/bin/dmesg"
ln -s "toybox_vendor" "/$vendor/bin/dos2unix"
ln -s "toybox_vendor" "/$vendor/bin/du"
ln -s "toybox_vendor" "/$vendor/bin/echo"
# ln -s "toybox_vendor" "/$vendor/bin/egrep" # bin-grep
ln -s "toybox_vendor" "/$vendor/bin/env"
ln -s "toybox_vendor" "/$vendor/bin/expand"
ln -s "toybox_vendor" "/$vendor/bin/expr"
ln -s "toybox_vendor" "/$vendor/bin/fallocate"
ln -s "toybox_vendor" "/$vendor/bin/false"
# ln -s "toybox_vendor" "/$vendor/bin/fgrep" # bin-grep
ln -s "toybox_vendor" "/$vendor/bin/file"
ln -s "toybox_vendor" "/$vendor/bin/find"
ln -s "toybox_vendor" "/$vendor/bin/flock"
ln -s "toybox_vendor" "/$vendor/bin/fmt"
ln -s "toybox_vendor" "/$vendor/bin/free"
ln -s "toybox_vendor" "/$vendor/bin/freeramdisk"
ln -s "toybox_vendor" "/$vendor/bin/fsfreeze"
ln -s "toybox_vendor" "/$vendor/bin/getenforce"
ln -s "toybox_vendor" "/$vendor/bin/getfattr"
# ln -s "toybox_vendor" "/$vendor/bin/grep" # bin-grep
ln -s "toybox_vendor" "/$vendor/bin/groups"
ln -s "toybox_vendor" "/$vendor/bin/gunzip"
ln -s "toybox_vendor" "/$vendor/bin/gzip"
ln -s "toybox_vendor" "/$vendor/bin/head"
ln -s "toybox_vendor" "/$vendor/bin/help"
ln -s "toybox_vendor" "/$vendor/bin/hostname"
ln -s "toybox_vendor" "/$vendor/bin/hwclock"
ln -s "toybox_vendor" "/$vendor/bin/id"
ln -s "toybox_vendor" "/$vendor/bin/ifconfig"
ln -s "toybox_vendor" "/$vendor/bin/inotifyd"
ln -s "toybox_vendor" "/$vendor/bin/insmod"
ln -s "toybox_vendor" "/$vendor/bin/install"
ln -s "toybox_vendor" "/$vendor/bin/ionice"
ln -s "toybox_vendor" "/$vendor/bin/iorenice"
# ln -s "toybox_vendor" "/$vendor/bin/iotop" # bug command
ln -s "toybox_vendor" "/$vendor/bin/kill"
ln -s "toybox_vendor" "/$vendor/bin/killall"
ln -s "toybox_vendor" "/$vendor/bin/ln"
ln -s "toybox_vendor" "/$vendor/bin/load_policy"
ln -s "toybox_vendor" "/$vendor/bin/log"
ln -s "toybox_vendor" "/$vendor/bin/logname"
ln -s "toybox_vendor" "/$vendor/bin/losetup"
ln -s "toybox_vendor" "/$vendor/bin/ls"
ln -s "toybox_vendor" "/$vendor/bin/lsattr"
ln -s "toybox_vendor" "/$vendor/bin/lsmod"
ln -s "toybox_vendor" "/$vendor/bin/lsof"
ln -s "toybox_vendor" "/$vendor/bin/lspci"
ln -s "toybox_vendor" "/$vendor/bin/lsusb"
ln -s "toybox_vendor" "/$vendor/bin/makedevs"
ln -s "toybox_vendor" "/$vendor/bin/md5sum"
ln -s "toybox_vendor" "/$vendor/bin/microcom"
ln -s "toybox_vendor" "/$vendor/bin/mkdir"
ln -s "toybox_vendor" "/$vendor/bin/mkfifo"
ln -s "toybox_vendor" "/$vendor/bin/mknod"
ln -s "toybox_vendor" "/$vendor/bin/mkswap"
ln -s "toybox_vendor" "/$vendor/bin/mktemp"
ln -s "toybox_vendor" "/$vendor/bin/modinfo"
ln -s "toybox_vendor" "/$vendor/bin/modprobe"
ln -s "toybox_vendor" "/$vendor/bin/more"
ln -s "toybox_vendor" "/$vendor/bin/mount"
ln -s "toybox_vendor" "/$vendor/bin/mountpoint"
ln -s "toybox_vendor" "/$vendor/bin/mv"
ln -s "toybox_vendor" "/$vendor/bin/nbd-client"
ln -s "toybox_vendor" "/$vendor/bin/nc"
ln -s "toybox_vendor" "/$vendor/bin/netcat"
ln -s "toybox_vendor" "/$vendor/bin/netstat"
ln -s "toybox_vendor" "/$vendor/bin/newfs_msdos"
ln -s "toybox_vendor" "/$vendor/bin/nice"
ln -s "toybox_vendor" "/$vendor/bin/nl"
ln -s "toybox_vendor" "/$vendor/bin/nohup"
ln -s "toybox_vendor" "/$vendor/bin/od"
ln -s "toybox_vendor" "/$vendor/bin/partprobe"
ln -s "toybox_vendor" "/$vendor/bin/paste"
ln -s "toybox_vendor" "/$vendor/bin/patch"
ln -s "toybox_vendor" "/$vendor/bin/pgrep"
ln -s "toybox_vendor" "/$vendor/bin/pidof"
ln -s "toybox_vendor" "/$vendor/bin/pivot_root"
ln -s "toybox_vendor" "/$vendor/bin/pkill"
ln -s "toybox_vendor" "/$vendor/bin/pmap"
ln -s "toybox_vendor" "/$vendor/bin/printenv"
ln -s "toybox_vendor" "/$vendor/bin/printf"
ln -s "toybox_vendor" "/$vendor/bin/ps"
ln -s "toybox_vendor" "/$vendor/bin/pwd"
ln -s "toybox_vendor" "/$vendor/bin/pwdx"
ln -s "toybox_vendor" "/$vendor/bin/readlink"
ln -s "toybox_vendor" "/$vendor/bin/realpath"
ln -s "toybox_vendor" "/$vendor/bin/renice"
ln -s "toybox_vendor" "/$vendor/bin/restorecon"
ln -s "toybox_vendor" "/$vendor/bin/rev"
ln -s "toybox_vendor" "/$vendor/bin/rfkill"
ln -s "toybox_vendor" "/$vendor/bin/rm"
ln -s "toybox_vendor" "/$vendor/bin/rmdir"
ln -s "toybox_vendor" "/$vendor/bin/rmmod"
ln -s "toybox_vendor" "/$vendor/bin/runcon"
ln -s "toybox_vendor" "/$vendor/bin/sed"
ln -s "toybox_vendor" "/$vendor/bin/sendevent"
ln -s "toybox_vendor" "/$vendor/bin/seq"
ln -s "toybox_vendor" "/$vendor/bin/setenforce"
ln -s "toybox_vendor" "/$vendor/bin/setfattr"
ln -s "toybox_vendor" "/$vendor/bin/setprop"
ln -s "toybox_vendor" "/$vendor/bin/setsid"
ln -s "toybox_vendor" "/$vendor/bin/sha1sum"
ln -s "toybox_vendor" "/$vendor/bin/sha224sum"
ln -s "toybox_vendor" "/$vendor/bin/sha256sum"
ln -s "toybox_vendor" "/$vendor/bin/sha384sum"
ln -s "toybox_vendor" "/$vendor/bin/sha512sum"
ln -s "toybox_vendor" "/$vendor/bin/sleep"
ln -s "toybox_vendor" "/$vendor/bin/sort"
ln -s "toybox_vendor" "/$vendor/bin/split"
ln -s "toybox_vendor" "/$vendor/bin/start"
ln -s "toybox_vendor" "/$vendor/bin/stat"
ln -s "toybox_vendor" "/$vendor/bin/stop"
ln -s "toybox_vendor" "/$vendor/bin/strings"
ln -s "toybox_vendor" "/$vendor/bin/stty"
ln -s "toybox_vendor" "/$vendor/bin/swapoff"
ln -s "toybox_vendor" "/$vendor/bin/swapon"
ln -s "toybox_vendor" "/$vendor/bin/sync"
ln -s "toybox_vendor" "/$vendor/bin/sysctl"
ln -s "toybox_vendor" "/$vendor/bin/tac"
ln -s "toybox_vendor" "/$vendor/bin/tail"
ln -s "toybox_vendor" "/$vendor/bin/tar"
ln -s "toybox_vendor" "/$vendor/bin/taskset"
ln -s "toybox_vendor" "/$vendor/bin/tee"
ln -s "toybox_vendor" "/$vendor/bin/time"
ln -s "toybox_vendor" "/$vendor/bin/timeout"
ln -s "toybox_vendor" "/$vendor/bin/top"
ln -s "toybox_vendor" "/$vendor/bin/touch"
ln -s "toybox_vendor" "/$vendor/bin/tr"
ln -s "toybox_vendor" "/$vendor/bin/traceroute"
ln -s "toybox_vendor" "/$vendor/bin/traceroute6"
ln -s "toybox_vendor" "/$vendor/bin/true"
ln -s "toybox_vendor" "/$vendor/bin/truncate"
ln -s "toybox_vendor" "/$vendor/bin/tty"
ln -s "toybox_vendor" "/$vendor/bin/tunctl"
ln -s "toybox_vendor" "/$vendor/bin/ulimit"
ln -s "toybox_vendor" "/$vendor/bin/umount"
ln -s "toybox_vendor" "/$vendor/bin/uname"
ln -s "toybox_vendor" "/$vendor/bin/uniq"
ln -s "toybox_vendor" "/$vendor/bin/unix2dos"
ln -s "toybox_vendor" "/$vendor/bin/uptime"
ln -s "toybox_vendor" "/$vendor/bin/usleep"
ln -s "toybox_vendor" "/$vendor/bin/uudecode"
ln -s "toybox_vendor" "/$vendor/bin/uuencode"
ln -s "toybox_vendor" "/$vendor/bin/vconfig"
ln -s "toybox_vendor" "/$vendor/bin/vmstat"
ln -s "toybox_vendor" "/$vendor/bin/wc"
ln -s "toybox_vendor" "/$vendor/bin/which"
ln -s "toybox_vendor" "/$vendor/bin/whoami"
ln -s "toybox_vendor" "/$vendor/bin/xargs"
ln -s "toybox_vendor" "/$vendor/bin/xxd"
ln -s "toybox_vendor" "/$vendor/bin/yes"
ln -s "toybox_vendor" "/$vendor/bin/zcat"

chcon -h u:object_r:vendor_toolbox_exec:s0 "/$vendor/bin/toybox_vendor"

sleep 0.2

name="busybox"
version="1.31.0 [2019.06.10]"

echo " - $name $version"

# 1.31.0 [2019.06.10] / 396 Applets [ARM 64]

chown 0.2000 "/$system/xbin/busybox"
chmod 0777 "/$system/xbin/busybox"

ln -s "busybox" "/$system/xbin/["
ln -s "busybox" "/$system/xbin/[["
ln -s "busybox" "/$system/xbin/acpid"
ln -s "busybox" "/$system/xbin/add-shell"
ln -s "busybox" "/$system/xbin/addgroup"
ln -s "busybox" "/$system/xbin/adduser"
ln -s "busybox" "/$system/xbin/adjtimex"
ln -s "busybox" "/$system/xbin/arch"
ln -s "busybox" "/$system/xbin/arp"
ln -s "busybox" "/$system/xbin/arping"
ln -s "busybox" "/$system/xbin/ash"
ln -s "busybox" "/$system/xbin/awk"
ln -s "busybox" "/$system/xbin/base64"
ln -s "busybox" "/$system/xbin/basename"
ln -s "busybox" "/$system/xbin/bc"
ln -s "busybox" "/$system/xbin/beep"
ln -s "busybox" "/$system/xbin/blkdiscard"
ln -s "busybox" "/$system/xbin/blkid"
ln -s "busybox" "/$system/xbin/blockdev"
ln -s "busybox" "/$system/xbin/bootchartd"
ln -s "busybox" "/$system/xbin/brctl"
ln -s "busybox" "/$system/xbin/bunzip2"
ln -s "busybox" "/$system/xbin/bzcat"
ln -s "busybox" "/$system/xbin/bzip2"
ln -s "busybox" "/$system/xbin/cal"
ln -s "busybox" "/$system/xbin/cat"
ln -s "busybox" "/$system/xbin/chat"
ln -s "busybox" "/$system/xbin/chattr"
ln -s "busybox" "/$system/xbin/chgrp"
ln -s "busybox" "/$system/xbin/chmod"
ln -s "busybox" "/$system/xbin/chown"
ln -s "busybox" "/$system/xbin/chpasswd"
ln -s "busybox" "/$system/xbin/chpst"
ln -s "busybox" "/$system/xbin/chroot"
ln -s "busybox" "/$system/xbin/chrt"
ln -s "busybox" "/$system/xbin/chvt"
ln -s "busybox" "/$system/xbin/cksum"
ln -s "busybox" "/$system/xbin/clear"
ln -s "busybox" "/$system/xbin/cmp"
ln -s "busybox" "/$system/xbin/comm"
ln -s "busybox" "/$system/xbin/conspy"
ln -s "busybox" "/$system/xbin/cp"
ln -s "busybox" "/$system/xbin/cpio"
ln -s "busybox" "/$system/xbin/crond"
ln -s "busybox" "/$system/xbin/crontab"
ln -s "busybox" "/$system/xbin/cryptpw"
ln -s "busybox" "/$system/xbin/cttyhack"
ln -s "busybox" "/$system/xbin/cut"
ln -s "busybox" "/$system/xbin/date"
ln -s "busybox" "/$system/xbin/dc"
ln -s "busybox" "/$system/xbin/dd"
ln -s "busybox" "/$system/xbin/deallocvt"
ln -s "busybox" "/$system/xbin/delgroup"
ln -s "busybox" "/$system/xbin/deluser"
ln -s "busybox" "/$system/xbin/depmod"
ln -s "busybox" "/$system/xbin/devmem"
ln -s "busybox" "/$system/xbin/df"
ln -s "busybox" "/$system/xbin/dhcprelay"
ln -s "busybox" "/$system/xbin/diff"
ln -s "busybox" "/$system/xbin/dirname"
ln -s "busybox" "/$system/xbin/dmesg"
ln -s "busybox" "/$system/xbin/dnsd"
ln -s "busybox" "/$system/xbin/dnsdomainname"
ln -s "busybox" "/$system/xbin/dos2unix"
ln -s "busybox" "/$system/xbin/dpkg"
ln -s "busybox" "/$system/xbin/dpkg-deb"
ln -s "busybox" "/$system/xbin/du"
ln -s "busybox" "/$system/xbin/dumpkmap"
ln -s "busybox" "/$system/xbin/dumpleases"
ln -s "busybox" "/$system/xbin/echo"
ln -s "busybox" "/$system/xbin/ed"
ln -s "busybox" "/$system/xbin/egrep"
ln -s "busybox" "/$system/xbin/eject"
ln -s "busybox" "/$system/xbin/env"
ln -s "busybox" "/$system/xbin/envdir"
ln -s "busybox" "/$system/xbin/envuidgid"
ln -s "busybox" "/$system/xbin/ether-wake"
ln -s "busybox" "/$system/xbin/expand"
ln -s "busybox" "/$system/xbin/expr"
ln -s "busybox" "/$system/xbin/factor"
ln -s "busybox" "/$system/xbin/fakeidentd"
ln -s "busybox" "/$system/xbin/fallocate"
ln -s "busybox" "/$system/xbin/false"
ln -s "busybox" "/$system/xbin/fatattr"
ln -s "busybox" "/$system/xbin/fbset"
ln -s "busybox" "/$system/xbin/fbsplash"
ln -s "busybox" "/$system/xbin/fdflush"
ln -s "busybox" "/$system/xbin/fdformat"
ln -s "busybox" "/$system/xbin/fdisk"
ln -s "busybox" "/$system/xbin/fgconsole"
ln -s "busybox" "/$system/xbin/fgrep"
ln -s "busybox" "/$system/xbin/find"
ln -s "busybox" "/$system/xbin/findfs"
ln -s "busybox" "/$system/xbin/flock"
ln -s "busybox" "/$system/xbin/fold"
ln -s "busybox" "/$system/xbin/free"
ln -s "busybox" "/$system/xbin/freeramdisk"
ln -s "busybox" "/$system/xbin/fsck"
ln -s "busybox" "/$system/xbin/fsck.minix"
ln -s "busybox" "/$system/xbin/fsfreeze"
ln -s "busybox" "/$system/xbin/fstrim"
ln -s "busybox" "/$system/xbin/fsync"
ln -s "busybox" "/$system/xbin/ftpd"
ln -s "busybox" "/$system/xbin/ftpget"
ln -s "busybox" "/$system/xbin/ftpput"
ln -s "busybox" "/$system/xbin/fuser"
ln -s "busybox" "/$system/xbin/getopt"
ln -s "busybox" "/$system/xbin/getty"
ln -s "busybox" "/$system/xbin/grep"
ln -s "busybox" "/$system/xbin/groups"
ln -s "busybox" "/$system/xbin/gunzip"
ln -s "busybox" "/$system/xbin/gzip"
ln -s "busybox" "/$system/xbin/halt"
ln -s "busybox" "/$system/xbin/hd"
ln -s "busybox" "/$system/xbin/hdparm"
ln -s "busybox" "/$system/xbin/head"
ln -s "busybox" "/$system/xbin/hexdump"
ln -s "busybox" "/$system/xbin/hexedit"
ln -s "busybox" "/$system/xbin/hostid"
ln -s "busybox" "/$system/xbin/hostname"
ln -s "busybox" "/$system/xbin/httpd"
ln -s "busybox" "/$system/xbin/hush"
ln -s "busybox" "/$system/xbin/hwclock"
ln -s "busybox" "/$system/xbin/i2cdetect"
ln -s "busybox" "/$system/xbin/i2cdump"
ln -s "busybox" "/$system/xbin/i2cget"
ln -s "busybox" "/$system/xbin/i2cset"
ln -s "busybox" "/$system/xbin/i2ctransfer"
ln -s "busybox" "/$system/xbin/id"
ln -s "busybox" "/$system/xbin/ifconfig"
ln -s "busybox" "/$system/xbin/ifdown"
ln -s "busybox" "/$system/xbin/ifenslave"
ln -s "busybox" "/$system/xbin/ifplugd"
ln -s "busybox" "/$system/xbin/ifup"
ln -s "busybox" "/$system/xbin/inetd"
ln -s "busybox" "/$system/xbin/init"
ln -s "busybox" "/$system/xbin/insmod"
ln -s "busybox" "/$system/xbin/install"
ln -s "busybox" "/$system/xbin/ionice"
ln -s "busybox" "/$system/xbin/iostat"
ln -s "busybox" "/$system/xbin/ip"
ln -s "busybox" "/$system/xbin/ipaddr"
ln -s "busybox" "/$system/xbin/ipcalc"
ln -s "busybox" "/$system/xbin/ipcrm"
ln -s "busybox" "/$system/xbin/ipcs"
ln -s "busybox" "/$system/xbin/iplink"
ln -s "busybox" "/$system/xbin/ipneigh"
ln -s "busybox" "/$system/xbin/iproute"
ln -s "busybox" "/$system/xbin/iprule"
ln -s "busybox" "/$system/xbin/iptunnel"
ln -s "busybox" "/$system/xbin/kbd_mode"
ln -s "busybox" "/$system/xbin/kill"
ln -s "busybox" "/$system/xbin/killall"
ln -s "busybox" "/$system/xbin/killall5"
ln -s "busybox" "/$system/xbin/klogd"
ln -s "busybox" "/$system/xbin/last"
ln -s "busybox" "/$system/xbin/less"
ln -s "busybox" "/$system/xbin/link"
ln -s "busybox" "/$system/xbin/linux32"
ln -s "busybox" "/$system/xbin/linux64"
ln -s "busybox" "/$system/xbin/linuxrc"
ln -s "busybox" "/$system/xbin/ln"
ln -s "busybox" "/$system/xbin/loadfont"
ln -s "busybox" "/$system/xbin/loadkmap"
ln -s "busybox" "/$system/xbin/logger"
ln -s "busybox" "/$system/xbin/login"
ln -s "busybox" "/$system/xbin/logname"
ln -s "busybox" "/$system/xbin/logread"
ln -s "busybox" "/$system/xbin/losetup"
ln -s "busybox" "/$system/xbin/lpd"
ln -s "busybox" "/$system/xbin/lpq"
ln -s "busybox" "/$system/xbin/lpr"
ln -s "busybox" "/$system/xbin/ls"
ln -s "busybox" "/$system/xbin/lsattr"
ln -s "busybox" "/$system/xbin/lsmod"
ln -s "busybox" "/$system/xbin/lsof"
ln -s "busybox" "/$system/xbin/lspci"
ln -s "busybox" "/$system/xbin/lsscsi"
ln -s "busybox" "/$system/xbin/lsusb"
ln -s "busybox" "/$system/xbin/lzcat"
ln -s "busybox" "/$system/xbin/lzma"
ln -s "busybox" "/$system/xbin/lzop"
ln -s "busybox" "/$system/xbin/makedevs"
ln -s "busybox" "/$system/xbin/makemime"
ln -s "busybox" "/$system/xbin/man"
ln -s "busybox" "/$system/xbin/md5sum"
ln -s "busybox" "/$system/xbin/mdev"
ln -s "busybox" "/$system/xbin/mesg"
ln -s "busybox" "/$system/xbin/microcom"
ln -s "busybox" "/$system/xbin/mkdir"
ln -s "busybox" "/$system/xbin/mkdosfs"
ln -s "busybox" "/$system/xbin/mke2fs"
ln -s "busybox" "/$system/xbin/mkfifo"
ln -s "busybox" "/$system/xbin/mkfs.ext2"
ln -s "busybox" "/$system/xbin/mkfs.minix"
ln -s "busybox" "/$system/xbin/mkfs.vfat"
ln -s "busybox" "/$system/xbin/mknod"
ln -s "busybox" "/$system/xbin/mkpasswd"
ln -s "busybox" "/$system/xbin/mkswap"
ln -s "busybox" "/$system/xbin/mktemp"
ln -s "busybox" "/$system/xbin/modinfo"
ln -s "busybox" "/$system/xbin/modprobe"
ln -s "busybox" "/$system/xbin/more"
ln -s "busybox" "/$system/xbin/mount"
ln -s "busybox" "/$system/xbin/mountpoint"
ln -s "busybox" "/$system/xbin/mpstat"
ln -s "busybox" "/$system/xbin/mt"
ln -s "busybox" "/$system/xbin/mv"
ln -s "busybox" "/$system/xbin/nameif"
ln -s "busybox" "/$system/xbin/nanddump"
ln -s "busybox" "/$system/xbin/nandwrite"
ln -s "busybox" "/$system/xbin/nbd-client"
ln -s "busybox" "/$system/xbin/nc"
ln -s "busybox" "/$system/xbin/netstat"
ln -s "busybox" "/$system/xbin/nice"
ln -s "busybox" "/$system/xbin/nl"
ln -s "busybox" "/$system/xbin/nmeter"
ln -s "busybox" "/$system/xbin/nohup"
ln -s "busybox" "/$system/xbin/nologin"
ln -s "busybox" "/$system/xbin/nproc"
ln -s "busybox" "/$system/xbin/nsenter"
ln -s "busybox" "/$system/xbin/nslookup"
ln -s "busybox" "/$system/xbin/ntpd"
ln -s "busybox" "/$system/xbin/nuke"
ln -s "busybox" "/$system/xbin/od"
ln -s "busybox" "/$system/xbin/openvt"
ln -s "busybox" "/$system/xbin/partprobe"
ln -s "busybox" "/$system/xbin/passwd"
ln -s "busybox" "/$system/xbin/paste"
ln -s "busybox" "/$system/xbin/patch"
ln -s "busybox" "/$system/xbin/pgrep"
ln -s "busybox" "/$system/xbin/pidof"
ln -s "busybox" "/$system/xbin/ping"
ln -s "busybox" "/$system/xbin/ping6"
ln -s "busybox" "/$system/xbin/pipe_progress"
ln -s "busybox" "/$system/xbin/pivot_root"
ln -s "busybox" "/$system/xbin/pkill"
ln -s "busybox" "/$system/xbin/pmap"
ln -s "busybox" "/$system/xbin/popmaildir"
ln -s "busybox" "/$system/xbin/poweroff"
ln -s "busybox" "/$system/xbin/powertop"
ln -s "busybox" "/$system/xbin/printenv"
ln -s "busybox" "/$system/xbin/printf"
ln -s "busybox" "/$system/xbin/ps"
ln -s "busybox" "/$system/xbin/pscan"
ln -s "busybox" "/$system/xbin/pstree"
ln -s "busybox" "/$system/xbin/pwd"
ln -s "busybox" "/$system/xbin/pwdx"
ln -s "busybox" "/$system/xbin/raidautorun"
ln -s "busybox" "/$system/xbin/rdate"
ln -s "busybox" "/$system/xbin/rdev"
ln -s "busybox" "/$system/xbin/readahead"
ln -s "busybox" "/$system/xbin/readlink"
ln -s "busybox" "/$system/xbin/readprofile"
ln -s "busybox" "/$system/xbin/realpath"
ln -s "busybox" "/$system/xbin/reboot"
ln -s "busybox" "/$system/xbin/reformime"
ln -s "busybox" "/$system/xbin/remove-shell"
ln -s "busybox" "/$system/xbin/renice"
ln -s "busybox" "/$system/xbin/reset"
ln -s "busybox" "/$system/xbin/resize"
ln -s "busybox" "/$system/xbin/resume"
ln -s "busybox" "/$system/xbin/rev"
ln -s "busybox" "/$system/xbin/rm"
ln -s "busybox" "/$system/xbin/rmdir"
ln -s "busybox" "/$system/xbin/rmmod"
ln -s "busybox" "/$system/xbin/route"
ln -s "busybox" "/$system/xbin/rpm"
ln -s "busybox" "/$system/xbin/rpm2cpio"
ln -s "busybox" "/$system/xbin/rtcwake"
ln -s "busybox" "/$system/xbin/run-init"
ln -s "busybox" "/$system/xbin/run-parts"
ln -s "busybox" "/$system/xbin/runlevel"
ln -s "busybox" "/$system/xbin/runsv"
ln -s "busybox" "/$system/xbin/runsvdir"
ln -s "busybox" "/$system/xbin/rx"
ln -s "busybox" "/$system/xbin/script"
ln -s "busybox" "/$system/xbin/scriptreplay"
ln -s "busybox" "/$system/xbin/sed"
ln -s "busybox" "/$system/xbin/sendmail"
ln -s "busybox" "/$system/xbin/seq"
ln -s "busybox" "/$system/xbin/setarch"
ln -s "busybox" "/$system/xbin/setconsole"
ln -s "busybox" "/$system/xbin/setfattr"
ln -s "busybox" "/$system/xbin/setfont"
ln -s "busybox" "/$system/xbin/setkeycodes"
ln -s "busybox" "/$system/xbin/setlogcons"
ln -s "busybox" "/$system/xbin/setpriv"
ln -s "busybox" "/$system/xbin/setserial"
ln -s "busybox" "/$system/xbin/setsid"
ln -s "busybox" "/$system/xbin/setuidgid"
ln -s "busybox" "/$system/xbin/sh"
ln -s "busybox" "/$system/xbin/sha1sum"
ln -s "busybox" "/$system/xbin/sha256sum"
ln -s "busybox" "/$system/xbin/sha3sum"
ln -s "busybox" "/$system/xbin/sha512sum"
ln -s "busybox" "/$system/xbin/showkey"
ln -s "busybox" "/$system/xbin/shred"
ln -s "busybox" "/$system/xbin/shuf"
ln -s "busybox" "/$system/xbin/slattach"
ln -s "busybox" "/$system/xbin/sleep"
ln -s "busybox" "/$system/xbin/smemcap"
ln -s "busybox" "/$system/xbin/softlimit"
ln -s "busybox" "/$system/xbin/sort"
ln -s "busybox" "/$system/xbin/split"
ln -s "busybox" "/$system/xbin/ssl_client"
ln -s "busybox" "/$system/xbin/start-stop-daemon"
ln -s "busybox" "/$system/xbin/stat"
ln -s "busybox" "/$system/xbin/strings"
ln -s "busybox" "/$system/xbin/stty"
# ln -s "busybox" "/$system/xbin/su" # hide command
ln -s "busybox" "/$system/xbin/sulogin"
ln -s "busybox" "/$system/xbin/sum"
ln -s "busybox" "/$system/xbin/sv"
ln -s "busybox" "/$system/xbin/svc"
ln -s "busybox" "/$system/xbin/svlogd"
ln -s "busybox" "/$system/xbin/svok"
ln -s "busybox" "/$system/xbin/swapoff"
ln -s "busybox" "/$system/xbin/swapon"
ln -s "busybox" "/$system/xbin/switch_root"
ln -s "busybox" "/$system/xbin/sync"
ln -s "busybox" "/$system/xbin/sysctl"
ln -s "busybox" "/$system/xbin/syslogd"
ln -s "busybox" "/$system/xbin/tac"
ln -s "busybox" "/$system/xbin/tail"
ln -s "busybox" "/$system/xbin/tar"
ln -s "busybox" "/$system/xbin/taskset"
ln -s "busybox" "/$system/xbin/tc"
ln -s "busybox" "/$system/xbin/tcpsvd"
ln -s "busybox" "/$system/xbin/tee"
ln -s "busybox" "/$system/xbin/telnet"
ln -s "busybox" "/$system/xbin/telnetd"
ln -s "busybox" "/$system/xbin/test"
ln -s "busybox" "/$system/xbin/tftp"
ln -s "busybox" "/$system/xbin/tftpd"
ln -s "busybox" "/$system/xbin/time"
ln -s "busybox" "/$system/xbin/timeout"
ln -s "busybox" "/$system/xbin/top"
ln -s "busybox" "/$system/xbin/touch"
ln -s "busybox" "/$system/xbin/tr"
ln -s "busybox" "/$system/xbin/traceroute"
ln -s "busybox" "/$system/xbin/traceroute6"
ln -s "busybox" "/$system/xbin/true"
ln -s "busybox" "/$system/xbin/truncate"
ln -s "busybox" "/$system/xbin/ts"
ln -s "busybox" "/$system/xbin/tty"
ln -s "busybox" "/$system/xbin/ttysize"
ln -s "busybox" "/$system/xbin/tunctl"
ln -s "busybox" "/$system/xbin/ubiattach"
ln -s "busybox" "/$system/xbin/ubidetach"
ln -s "busybox" "/$system/xbin/ubimkvol"
ln -s "busybox" "/$system/xbin/ubirename"
ln -s "busybox" "/$system/xbin/ubirmvol"
ln -s "busybox" "/$system/xbin/ubirsvol"
ln -s "busybox" "/$system/xbin/ubiupdatevol"
ln -s "busybox" "/$system/xbin/udhcpc"
ln -s "busybox" "/$system/xbin/udhcpc6"
ln -s "busybox" "/$system/xbin/udhcpd"
ln -s "busybox" "/$system/xbin/udpsvd"
ln -s "busybox" "/$system/xbin/uevent"
ln -s "busybox" "/$system/xbin/umount"
ln -s "busybox" "/$system/xbin/uname"
ln -s "busybox" "/$system/xbin/unexpand"
ln -s "busybox" "/$system/xbin/uniq"
ln -s "busybox" "/$system/xbin/unix2dos"
ln -s "busybox" "/$system/xbin/unlink"
ln -s "busybox" "/$system/xbin/unlzma"
ln -s "busybox" "/$system/xbin/unshare"
ln -s "busybox" "/$system/xbin/unxz"
ln -s "busybox" "/$system/xbin/unzip"
ln -s "busybox" "/$system/xbin/uptime"
ln -s "busybox" "/$system/xbin/users"
ln -s "busybox" "/$system/xbin/usleep"
ln -s "busybox" "/$system/xbin/uudecode"
ln -s "busybox" "/$system/xbin/uuencode"
ln -s "busybox" "/$system/xbin/vconfig"
ln -s "busybox" "/$system/xbin/vi"
ln -s "busybox" "/$system/xbin/vlock"
ln -s "busybox" "/$system/xbin/volname"
ln -s "busybox" "/$system/xbin/w"
ln -s "busybox" "/$system/xbin/wall"
ln -s "busybox" "/$system/xbin/watch"
ln -s "busybox" "/$system/xbin/watchdog"
ln -s "busybox" "/$system/xbin/wc"
ln -s "busybox" "/$system/xbin/wget"
ln -s "busybox" "/$system/xbin/which"
ln -s "busybox" "/$system/xbin/who"
ln -s "busybox" "/$system/xbin/whoami"
ln -s "busybox" "/$system/xbin/whois"
ln -s "busybox" "/$system/xbin/xargs"
ln -s "busybox" "/$system/xbin/xxd"
ln -s "busybox" "/$system/xbin/xz"
ln -s "busybox" "/$system/xbin/xzcat"
ln -s "busybox" "/$system/xbin/yes"
ln -s "busybox" "/$system/xbin/zcat"
ln -s "busybox" "/$system/xbin/zcip"

sleep 0.2

name="android-tools"
version="1.0.39"

echo " - $name $version"

# 1.0.39

chown 0.0 "/$system/bin/adb"
chmod 0755 "/$system/bin/adb"

chcon -h u:object_r:adb_exec:s0 "/$system/bin/adb"

chown 0.0 "/$system/bin/adb.bin"
chmod 0755 "/$system/bin/adb.bin"

# 1.0.40

chown 0.2000 "/$system/bin/adbd"
chmod 0755 "/$system/bin/adbd"

chcon -h u:object_r:adbd_exec:s0 "/$system/bin/adbd"

chown 0.0 "/$system/lib/libadbconnection.so"
chmod 0644 "/$system/lib/libadbconnection.so"

chown 0.0 "/$system/lib/libadbconnectiond.so"
chmod 0644 "/$system/lib/libadbconnectiond.so"

chown 0.0 "/$system/lib64/libadbconnection.so"
chmod 0644 "/$system/lib64/libadbconnection.so"

chown 0.0 "/$system/lib64/libadbconnectiond.so"
chmod 0644 "/$system/lib64/libadbconnectiond.so"

# 1.0

chown 0.2000 "/$system/bin/e2fsdroid"
chmod 0755 "/$system/bin/e2fsdroid"

chcon -h u:object_r:e2fs_exec:s0 "/$system/bin/e2fsdroid"

# 8.0.0 - 20171217.042620 [2017.12.17]

chown 0.0 "/$system/bin/fastboot"
chmod 0755 "/$system/bin/fastboot"

# 3.5

chown 0.2000 "/$system/bin/mkbootimg"
chmod 0755 "/$system/bin/mkbootimg"

sleep 0.2

name="fstrim"
version="2.34.150 [9245 C]"

echo " - $name $version"

# 2.34.150 [9245 C]

chown 0.2000 "/$system/bin/fstrim"
chmod 0755 "/$system/bin/fstrim"

sleep 0.2

name="zygote_restart"
version="19.5"

echo " - $name $version"

# 19.5

chown 0.2000 "/$system/bin/zygote_restart"
chmod 0755 "/$system/bin/zygote_restart"

sleep 0.2
