# Shell script (sh)

name="coreutils"
version="8.31"

if [ -d "/system/system" ]; then
	system="system/system"
	vendor="vendor"
else
	system="system"
	vendor="vendor"
fi

# 8.31

chown 0.2000 "/$system/bin/coreutils"
chmod 0755 "/$system/bin/coreutils"

ln -s "coreutils" "/$system/bin/["
ln -s "coreutils" "/$system/bin/b2sum"
ln -s "coreutils" "/$system/bin/base32"
ln -s "coreutils" "/$system/bin/base64"
ln -s "coreutils" "/$system/bin/basename"
ln -s "coreutils" "/$system/bin/basenc"
ln -s "coreutils" "/$system/bin/cat"
ln -s "coreutils" "/$system/bin/chcon"
ln -s "coreutils" "/$system/bin/chgrp"
ln -s "coreutils" "/$system/bin/chmod"
ln -s "coreutils" "/$system/bin/chown"
ln -s "coreutils" "/$system/bin/chroot"
ln -s "coreutils" "/$system/bin/cksum"
ln -s "coreutils" "/$system/bin/comm"
ln -sf "coreutils" "/$system/bin/cp" # bin-toybox (better)
ln -s "coreutils" "/$system/bin/csplit"
ln -s "coreutils" "/$system/bin/cut"
ln -s "coreutils" "/$system/bin/date" # bin-toolbox / xbin-date
ln -s "coreutils" "/$system/bin/dd" # bin-toybox / xbin-dd
ln -s "coreutils" "/$system/bin/df"
ln -s "coreutils" "/$system/bin/dir"
ln -s "coreutils" "/$system/bin/dircolors"
ln -s "coreutils" "/$system/bin/dirname"
ln -s "coreutils" "/$system/bin/du"
ln -s "coreutils" "/$system/bin/echo"
ln -s "coreutils" "/$system/bin/env"
ln -s "coreutils" "/$system/bin/expand"
ln -s "coreutils" "/$system/bin/expr"
ln -s "coreutils" "/$system/bin/factor"
ln -s "coreutils" "/$system/bin/false"
ln -s "coreutils" "/$system/bin/fmt"
ln -s "coreutils" "/$system/bin/fold"
ln -s "coreutils" "/$system/bin/ginstall"
ln -s "coreutils" "/$system/bin/groups"
ln -s "coreutils" "/$system/bin/head"
ln -s "coreutils" "/$system/bin/hostid"
ln -s "coreutils" "/$system/bin/id"
ln -s "coreutils" "/$system/bin/join"
ln -s "coreutils" "/$system/bin/kill"
ln -s "coreutils" "/$system/bin/link"
ln -s "coreutils" "/$system/bin/ln"
ln -s "coreutils" "/$system/bin/logname"
ln -s "coreutils" "/$system/bin/ls" # bin-toybox / xbin-busybox / xbin-ls
ln -s "coreutils" "/$system/bin/md5sum"
ln -s "coreutils" "/$system/bin/mkdir"
ln -s "coreutils" "/$system/bin/mkfifo"
ln -s "coreutils" "/$system/bin/mknod"
ln -s "coreutils" "/$system/bin/mktemp"
ln -sf "coreutils" "/$system/bin/mv" # bin-toybox (better)
ln -s "coreutils" "/$system/bin/nice"
ln -s "coreutils" "/$system/bin/nl"
ln -s "coreutils" "/$system/bin/nohup"
ln -s "coreutils" "/$system/bin/nproc"
ln -s "coreutils" "/$system/bin/numfmt"
ln -s "coreutils" "/$system/bin/od"
ln -s "coreutils" "/$system/bin/paste"
ln -s "coreutils" "/$system/bin/pathchk"
ln -s "coreutils" "/$system/bin/pinky"
ln -s "coreutils" "/$system/bin/pr"
ln -s "coreutils" "/$system/bin/printenv"
ln -s "coreutils" "/$system/bin/printf"
ln -s "coreutils" "/$system/bin/ptx"
ln -s "coreutils" "/$system/bin/pwd"
ln -s "coreutils" "/$system/bin/readlink"
ln -s "coreutils" "/$system/bin/realpath"
ln -s "coreutils" "/$system/bin/rm"
ln -s "coreutils" "/$system/bin/rmdir"
ln -s "coreutils" "/$system/bin/runcon"
ln -s "coreutils" "/$system/bin/seq"
ln -s "coreutils" "/$system/bin/sha1sum"
ln -s "coreutils" "/$system/bin/sha224sum"
ln -s "coreutils" "/$system/bin/sha256sum"
ln -s "coreutils" "/$system/bin/sha384sum"
ln -s "coreutils" "/$system/bin/sha512sum"
ln -s "coreutils" "/$system/bin/shred"
ln -s "coreutils" "/$system/bin/shuf"
ln -s "coreutils" "/$system/bin/sleep"
ln -s "coreutils" "/$system/bin/split"
ln -s "coreutils" "/$system/bin/stat"
ln -s "coreutils" "/$system/bin/stdbuf"
ln -s "coreutils" "/$system/bin/stty"
ln -s "coreutils" "/$system/bin/sum"
ln -s "coreutils" "/$system/bin/sync"
ln -s "coreutils" "/$system/bin/tac"
ln -s "coreutils" "/$system/bin/tail"
ln -s "coreutils" "/$system/bin/tee"
ln -s "coreutils" "/$system/bin/test"
ln -s "coreutils" "/$system/bin/touch"
ln -s "coreutils" "/$system/bin/tr"
ln -s "coreutils" "/$system/bin/true"
ln -s "coreutils" "/$system/bin/truncate"
ln -s "coreutils" "/$system/bin/tsort"
ln -s "coreutils" "/$system/bin/tty"
ln -s "coreutils" "/$system/bin/uname"
ln -s "coreutils" "/$system/bin/unexpand"
ln -s "coreutils" "/$system/bin/uniq"
ln -s "coreutils" "/$system/bin/unlink"
ln -s "coreutils" "/$system/bin/uptime"
ln -s "coreutils" "/$system/bin/users"
ln -s "coreutils" "/$system/bin/vdir"
ln -s "coreutils" "/$system/bin/wc"
ln -s "coreutils" "/$system/bin/who"
ln -s "coreutils" "/$system/bin/whoami"
ln -s "coreutils" "/$system/bin/yes"

chown 0.2000 "/$system/xbin/sleep"
chmod 0755 "/$system/xbin/sleep"

chown 0.2000 "/$system/xbin/sort"
chmod 0755 "/$system/xbin/sort"

chown 0.2000 "/$system/xbin/timeout"
chmod 0755 "/$system/xbin/timeout"

# 8.28

chown 0.2000 "/$system/xbin/date"
chmod 0755 "/$system/xbin/date"

# 8.13

chown 0.2000 "/$system/xbin/dd"
chmod 0755 "/$system/xbin/dd"

# 1.0

chown 0.2000 "/$system/xbin/ls"
chmod 0755 "/$system/xbin/ls"
