# Shell script (sh)

name="toybox"
version="0.8.0 Android"

if [ -d "/system/system" ]; then
	system="system/system"
	vendor="vendor"
else
	system="system"
	vendor="vendor"
fi

# 0.8.0 Android / 196 Applets [ARM 64]

chown 0.2000 "/$system/bin/toybox"
chmod 0755 "/$system/bin/toybox"

ln -s "toybox" "/$system/bin/acpi"
ln -s "toybox" "/$system/bin/base64"
ln -s "toybox" "/$system/bin/basename"
ln -s "toybox" "/$system/bin/bc" # bin-bc
# ln -s "toybox" "/$system/bin/blkid" # bin-blkid
ln -s "toybox" "/$system/bin/blockdev"
ln -s "toybox" "/$system/bin/cal"
ln -s "toybox" "/$system/bin/cat"
ln -s "toybox" "/$system/bin/chattr"
ln -s "toybox" "/$system/bin/chcon"
ln -s "toybox" "/$system/bin/chgrp"
ln -s "toybox" "/$system/bin/chmod"
ln -s "toybox" "/$system/bin/chown"
ln -s "toybox" "/$system/bin/chroot"
ln -s "toybox" "/$system/bin/chrt"
ln -s "toybox" "/$system/bin/cksum"
ln -s "toybox" "/$system/bin/clear"
ln -s "toybox" "/$system/bin/cmp"
ln -s "toybox" "/$system/bin/comm"
ln -s "toybox" "/$system/bin/cp"
ln -s "toybox" "/$system/bin/cpio"
ln -s "toybox" "/$system/bin/cut"
ln -s "toybox" "/$system/bin/date"
# ln -s "toybox" "/$system/bin/dd" # bin-toolbox
ln -s "toybox" "/$system/bin/devmem"
ln -s "toybox" "/$system/bin/df"
ln -s "toybox" "/$system/bin/diff"
ln -s "toybox" "/$system/bin/dirname"
ln -s "toybox" "/$system/bin/dmesg"
ln -s "toybox" "/$system/bin/dos2unix"
ln -s "toybox" "/$system/bin/du"
ln -s "toybox" "/$system/bin/echo"
# ln -s "toybox" "/$system/bin/egrep" # bin-grep
ln -s "toybox" "/$system/bin/env"
ln -s "toybox" "/$system/bin/expand"
ln -s "toybox" "/$system/bin/expr"
ln -s "toybox" "/$system/bin/fallocate"
ln -s "toybox" "/$system/bin/false"
# ln -s "toybox" "/$system/bin/fgrep" # bin-grep
ln -s "toybox" "/$system/bin/file"
ln -s "toybox" "/$system/bin/find"
ln -s "toybox" "/$system/bin/flock"
ln -s "toybox" "/$system/bin/fmt"
ln -s "toybox" "/$system/bin/free"
ln -s "toybox" "/$system/bin/freeramdisk"
ln -s "toybox" "/$system/bin/fsfreeze"
ln -s "toybox" "/$system/bin/fsync"
ln -s "toybox" "/$system/bin/getconf"
ln -s "toybox" "/$system/bin/getenforce"
ln -s "toybox" "/$system/bin/getfattr"
# ln -s "toybox" "/$system/bin/grep" # bin-grep
ln -s "toybox" "/$system/bin/groups"
ln -s "toybox" "/$system/bin/gunzip" # bin-pigz / xbin-busybox
ln -s "toybox" "/$system/bin/gzip" # bin-pigz / xbin-busybox
ln -s "toybox" "/$system/bin/head"
ln -s "toybox" "/$system/bin/help"
ln -s "toybox" "/$system/bin/hostname"
ln -s "toybox" "/$system/bin/hwclock"
ln -s "toybox" "/$system/bin/i2cdetect" # bin-i2cdetect
ln -s "toybox" "/$system/bin/i2cdump" # bin-i2cdump
ln -s "toybox" "/$system/bin/i2cget" # bin-i2cget
ln -s "toybox" "/$system/bin/i2cset" # bin-i2cset
ln -s "toybox" "/$system/bin/iconv"
ln -s "toybox" "/$system/bin/id"
ln -s "toybox" "/$system/bin/ifconfig"
ln -s "toybox" "/$system/bin/inotifyd"
ln -s "toybox" "/$system/bin/insmod"
ln -s "toybox" "/$system/bin/install"
ln -s "toybox" "/$system/bin/ionice"
ln -s "toybox" "/$system/bin/iorenice"
ln -s "toybox" "/$system/bin/iotop" # bin-iotop
ln -s "toybox" "/$system/bin/kill"
ln -s "toybox" "/$system/bin/killall"
ln -s "toybox" "/$system/bin/ln"
ln -s "toybox" "/$system/bin/load_policy"
ln -s "toybox" "/$system/bin/log"
ln -s "toybox" "/$system/bin/logname"
ln -s "toybox" "/$system/bin/losetup"
ln -s "toybox" "/$system/bin/ls"
ln -s "toybox" "/$system/bin/lsattr"
ln -s "toybox" "/$system/bin/lsmod"
ln -s "toybox" "/$system/bin/lsof"
ln -s "toybox" "/$system/bin/lspci"
ln -s "toybox" "/$system/bin/lsusb"
ln -s "toybox" "/$system/bin/makedevs"
ln -s "toybox" "/$system/bin/md5sum"
ln -s "toybox" "/$system/bin/microcom"
ln -s "toybox" "/$system/bin/mkdir"
ln -s "toybox" "/$system/bin/mkfifo"
ln -s "toybox" "/$system/bin/mknod"
ln -s "toybox" "/$system/bin/mkswap"
ln -s "toybox" "/$system/bin/mktemp"
ln -s "toybox" "/$system/bin/modinfo"
ln -s "toybox" "/$system/bin/modprobe"
ln -s "toybox" "/$system/bin/more"
ln -s "toybox" "/$system/bin/mount"
ln -s "toybox" "/$system/bin/mountpoint"
ln -s "toybox" "/$system/bin/mv"
ln -s "toybox" "/$system/bin/nbd-client"
ln -s "toybox" "/$system/bin/nc"
ln -s "toybox" "/$system/bin/netcat"
ln -s "toybox" "/$system/bin/netstat"
ln -s "toybox" "/$system/bin/nice"
ln -s "toybox" "/$system/bin/nl"
ln -s "toybox" "/$system/bin/nohup"
ln -s "toybox" "/$system/bin/nproc"
ln -s "toybox" "/$system/bin/nsenter"
ln -s "toybox" "/$system/bin/od"
ln -s "toybox" "/$system/bin/partprobe"
ln -s "toybox" "/$system/bin/paste"
ln -s "toybox" "/$system/bin/patch"
ln -s "toybox" "/$system/bin/pgrep"
ln -s "toybox" "/$system/bin/pidof"
ln -s "toybox" "/$system/bin/ping" # bin-ping
ln -s "toybox" "/$system/bin/ping6" # bin-ping6
ln -s "toybox" "/$system/bin/pivot_root"
ln -s "toybox" "/$system/bin/pkill"
ln -s "toybox" "/$system/bin/pmap"
ln -s "toybox" "/$system/bin/printenv"
ln -s "toybox" "/$system/bin/printf"
ln -s "toybox" "/$system/bin/prlimit"
ln -s "toybox" "/$system/bin/ps"
ln -s "toybox" "/$system/bin/pwd"
ln -s "toybox" "/$system/bin/pwdx"
ln -s "toybox" "/$system/bin/readlink"
ln -s "toybox" "/$system/bin/realpath"
ln -s "toybox" "/$system/bin/renice"
ln -s "toybox" "/$system/bin/restorecon"
ln -s "toybox" "/$system/bin/rev"
ln -s "toybox" "/$system/bin/rfkill"
ln -s "toybox" "/$system/bin/rm"
ln -s "toybox" "/$system/bin/rmdir"
ln -s "toybox" "/$system/bin/rmmod"
ln -s "toybox" "/$system/bin/runcon"
ln -s "toybox" "/$system/bin/sed"
ln -s "toybox" "/$system/bin/sendevent"
ln -s "toybox" "/$system/bin/seq"
ln -s "toybox" "/$system/bin/setenforce"
ln -s "toybox" "/$system/bin/setfattr"
ln -s "toybox" "/$system/bin/setprop"
ln -s "toybox" "/$system/bin/setsid"
ln -s "toybox" "/$system/bin/sha1sum"
ln -s "toybox" "/$system/bin/sha224sum"
ln -s "toybox" "/$system/bin/sha256sum"
ln -s "toybox" "/$system/bin/sha384sum"
ln -s "toybox" "/$system/bin/sha512sum"
ln -s "toybox" "/$system/bin/sleep"
ln -s "toybox" "/$system/bin/sort"
ln -s "toybox" "/$system/bin/split"
ln -s "toybox" "/$system/bin/start"
ln -s "toybox" "/$system/bin/stat" # bin-stat
ln -s "toybox" "/$system/bin/stop"
ln -s "toybox" "/$system/bin/strings" # bin-strings
ln -s "toybox" "/$system/bin/stty"
ln -s "toybox" "/$system/bin/swapoff"
ln -s "toybox" "/$system/bin/swapon"
ln -s "toybox" "/$system/bin/sync"
ln -s "toybox" "/$system/bin/sysctl"
ln -s "toybox" "/$system/bin/tac"
ln -s "toybox" "/$system/bin/tail"
ln -s "toybox" "/$system/bin/tar"
ln -s "toybox" "/$system/bin/taskset"
ln -s "toybox" "/$system/bin/tee"
ln -s "toybox" "/$system/bin/time"
ln -s "toybox" "/$system/bin/timeout"
ln -s "toybox" "/$system/bin/top"
ln -s "toybox" "/$system/bin/touch"
ln -s "toybox" "/$system/bin/tr"
ln -s "toybox" "/$system/bin/traceroute" # bin-traceroute
ln -s "toybox" "/$system/bin/traceroute6" # bin-traceroute6
ln -s "toybox" "/$system/bin/true"
ln -s "toybox" "/$system/bin/truncate"
ln -s "toybox" "/$system/bin/tty"
ln -s "toybox" "/$system/bin/tunctl"
ln -s "toybox" "/$system/bin/ulimit"
ln -s "toybox" "/$system/bin/umount"
ln -s "toybox" "/$system/bin/uname"
ln -s "toybox" "/$system/bin/uniq"
ln -s "toybox" "/$system/bin/unix2dos"
ln -s "toybox" "/$system/bin/unlink"
ln -s "toybox" "/$system/bin/unshare"
ln -s "toybox" "/$system/bin/uptime"
ln -s "toybox" "/$system/bin/usleep"
ln -s "toybox" "/$system/bin/uudecode"
ln -s "toybox" "/$system/bin/uuencode"
ln -s "toybox" "/$system/bin/uuidgen"
ln -s "toybox" "/$system/bin/vconfig"
ln -s "toybox" "/$system/bin/vmstat"
ln -s "toybox" "/$system/bin/watch"
ln -s "toybox" "/$system/bin/wc"
ln -s "toybox" "/$system/bin/which"
ln -s "toybox" "/$system/bin/whoami"
ln -s "toybox" "/$system/bin/xargs"
ln -s "toybox" "/$system/bin/xxd"
ln -s "toybox" "/$system/bin/yes"
ln -s "toybox" "/$system/bin/zcat" # bin-pigz / xbin-busybox

chcon -h u:object_r:toolbox_exec:s0 "/$system/bin/toybox"

# 0.7.6 Android / 178 Applets [ARM 64]

chown 0.2000 "/$vendor/bin/toybox_vendor"
chmod 0755 "/$vendor/bin/toybox_vendor"

ln -s "toybox_vendor" "/$vendor/bin/acpi"
ln -s "toybox_vendor" "/$vendor/bin/base64"
ln -s "toybox_vendor" "/$vendor/bin/basename"
# ln -s "toybox_vendor" "/$vendor/bin/blkid" # bug comman
ln -s "toybox_vendor" "/$vendor/bin/blockdev"
ln -s "toybox_vendor" "/$vendor/bin/cal"
ln -s "toybox_vendor" "/$vendor/bin/cat"
ln -s "toybox_vendor" "/$vendor/bin/chattr"
ln -s "toybox_vendor" "/$vendor/bin/chcon"
ln -s "toybox_vendor" "/$vendor/bin/chgrp"
ln -s "toybox_vendor" "/$vendor/bin/chmod"
ln -s "toybox_vendor" "/$vendor/bin/chown"
ln -s "toybox_vendor" "/$vendor/bin/chroot"
ln -s "toybox_vendor" "/$vendor/bin/chrt"
ln -s "toybox_vendor" "/$vendor/bin/cksum"
ln -s "toybox_vendor" "/$vendor/bin/clear"
ln -s "toybox_vendor" "/$vendor/bin/cmp"
ln -s "toybox_vendor" "/$vendor/bin/comm"
ln -s "toybox_vendor" "/$vendor/bin/cp"
ln -s "toybox_vendor" "/$vendor/bin/cpio"
ln -s "toybox_vendor" "/$vendor/bin/cut"
ln -s "toybox_vendor" "/$vendor/bin/date"
# ln -s "toybox_vendor" "/$vendor/bin/dd" # bin-toolbox
ln -s "toybox_vendor" "/$vendor/bin/df"
ln -s "toybox_vendor" "/$vendor/bin/diff"
ln -s "toybox_vendor" "/$vendor/bin/dirname"
ln -s "toybox_vendor" "/$vendor/bin/dmesg"
ln -s "toybox_vendor" "/$vendor/bin/dos2unix"
ln -s "toybox_vendor" "/$vendor/bin/du"
ln -s "toybox_vendor" "/$vendor/bin/echo"
# ln -s "toybox_vendor" "/$vendor/bin/egrep" # bin-grep
ln -s "toybox_vendor" "/$vendor/bin/env"
ln -s "toybox_vendor" "/$vendor/bin/expand"
ln -s "toybox_vendor" "/$vendor/bin/expr"
ln -s "toybox_vendor" "/$vendor/bin/fallocate"
ln -s "toybox_vendor" "/$vendor/bin/false"
# ln -s "toybox_vendor" "/$vendor/bin/fgrep" # bin-grep
ln -s "toybox_vendor" "/$vendor/bin/file"
ln -s "toybox_vendor" "/$vendor/bin/find"
ln -s "toybox_vendor" "/$vendor/bin/flock"
ln -s "toybox_vendor" "/$vendor/bin/fmt"
ln -s "toybox_vendor" "/$vendor/bin/free"
ln -s "toybox_vendor" "/$vendor/bin/freeramdisk"
ln -s "toybox_vendor" "/$vendor/bin/fsfreeze"
ln -s "toybox_vendor" "/$vendor/bin/getenforce"
ln -s "toybox_vendor" "/$vendor/bin/getfattr"
# ln -s "toybox_vendor" "/$vendor/bin/grep" # bin-grep
ln -s "toybox_vendor" "/$vendor/bin/groups"
ln -s "toybox_vendor" "/$vendor/bin/gunzip"
ln -s "toybox_vendor" "/$vendor/bin/gzip"
ln -s "toybox_vendor" "/$vendor/bin/head"
ln -s "toybox_vendor" "/$vendor/bin/help"
ln -s "toybox_vendor" "/$vendor/bin/hostname"
ln -s "toybox_vendor" "/$vendor/bin/hwclock"
ln -s "toybox_vendor" "/$vendor/bin/id"
ln -s "toybox_vendor" "/$vendor/bin/ifconfig"
ln -s "toybox_vendor" "/$vendor/bin/inotifyd"
ln -s "toybox_vendor" "/$vendor/bin/insmod"
ln -s "toybox_vendor" "/$vendor/bin/install"
ln -s "toybox_vendor" "/$vendor/bin/ionice"
ln -s "toybox_vendor" "/$vendor/bin/iorenice"
# ln -s "toybox_vendor" "/$vendor/bin/iotop" # bug command
ln -s "toybox_vendor" "/$vendor/bin/kill"
ln -s "toybox_vendor" "/$vendor/bin/killall"
ln -s "toybox_vendor" "/$vendor/bin/ln"
ln -s "toybox_vendor" "/$vendor/bin/load_policy"
ln -s "toybox_vendor" "/$vendor/bin/log"
ln -s "toybox_vendor" "/$vendor/bin/logname"
ln -s "toybox_vendor" "/$vendor/bin/losetup"
ln -s "toybox_vendor" "/$vendor/bin/ls"
ln -s "toybox_vendor" "/$vendor/bin/lsattr"
ln -s "toybox_vendor" "/$vendor/bin/lsmod"
ln -s "toybox_vendor" "/$vendor/bin/lsof"
ln -s "toybox_vendor" "/$vendor/bin/lspci"
ln -s "toybox_vendor" "/$vendor/bin/lsusb"
ln -s "toybox_vendor" "/$vendor/bin/makedevs"
ln -s "toybox_vendor" "/$vendor/bin/md5sum"
ln -s "toybox_vendor" "/$vendor/bin/microcom"
ln -s "toybox_vendor" "/$vendor/bin/mkdir"
ln -s "toybox_vendor" "/$vendor/bin/mkfifo"
ln -s "toybox_vendor" "/$vendor/bin/mknod"
ln -s "toybox_vendor" "/$vendor/bin/mkswap"
ln -s "toybox_vendor" "/$vendor/bin/mktemp"
ln -s "toybox_vendor" "/$vendor/bin/modinfo"
ln -s "toybox_vendor" "/$vendor/bin/modprobe"
ln -s "toybox_vendor" "/$vendor/bin/more"
ln -s "toybox_vendor" "/$vendor/bin/mount"
ln -s "toybox_vendor" "/$vendor/bin/mountpoint"
ln -s "toybox_vendor" "/$vendor/bin/mv"
ln -s "toybox_vendor" "/$vendor/bin/nbd-client"
ln -s "toybox_vendor" "/$vendor/bin/nc"
ln -s "toybox_vendor" "/$vendor/bin/netcat"
ln -s "toybox_vendor" "/$vendor/bin/netstat"
ln -s "toybox_vendor" "/$vendor/bin/newfs_msdos"
ln -s "toybox_vendor" "/$vendor/bin/nice"
ln -s "toybox_vendor" "/$vendor/bin/nl"
ln -s "toybox_vendor" "/$vendor/bin/nohup"
ln -s "toybox_vendor" "/$vendor/bin/od"
ln -s "toybox_vendor" "/$vendor/bin/partprobe"
ln -s "toybox_vendor" "/$vendor/bin/paste"
ln -s "toybox_vendor" "/$vendor/bin/patch"
ln -s "toybox_vendor" "/$vendor/bin/pgrep"
ln -s "toybox_vendor" "/$vendor/bin/pidof"
ln -s "toybox_vendor" "/$vendor/bin/pivot_root"
ln -s "toybox_vendor" "/$vendor/bin/pkill"
ln -s "toybox_vendor" "/$vendor/bin/pmap"
ln -s "toybox_vendor" "/$vendor/bin/printenv"
ln -s "toybox_vendor" "/$vendor/bin/printf"
ln -s "toybox_vendor" "/$vendor/bin/ps"
ln -s "toybox_vendor" "/$vendor/bin/pwd"
ln -s "toybox_vendor" "/$vendor/bin/pwdx"
ln -s "toybox_vendor" "/$vendor/bin/readlink"
ln -s "toybox_vendor" "/$vendor/bin/realpath"
ln -s "toybox_vendor" "/$vendor/bin/renice"
ln -s "toybox_vendor" "/$vendor/bin/restorecon"
ln -s "toybox_vendor" "/$vendor/bin/rev"
ln -s "toybox_vendor" "/$vendor/bin/rfkill"
ln -s "toybox_vendor" "/$vendor/bin/rm"
ln -s "toybox_vendor" "/$vendor/bin/rmdir"
ln -s "toybox_vendor" "/$vendor/bin/rmmod"
ln -s "toybox_vendor" "/$vendor/bin/runcon"
ln -s "toybox_vendor" "/$vendor/bin/sed"
ln -s "toybox_vendor" "/$vendor/bin/sendevent"
ln -s "toybox_vendor" "/$vendor/bin/seq"
ln -s "toybox_vendor" "/$vendor/bin/setenforce"
ln -s "toybox_vendor" "/$vendor/bin/setfattr"
ln -s "toybox_vendor" "/$vendor/bin/setprop"
ln -s "toybox_vendor" "/$vendor/bin/setsid"
ln -s "toybox_vendor" "/$vendor/bin/sha1sum"
ln -s "toybox_vendor" "/$vendor/bin/sha224sum"
ln -s "toybox_vendor" "/$vendor/bin/sha256sum"
ln -s "toybox_vendor" "/$vendor/bin/sha384sum"
ln -s "toybox_vendor" "/$vendor/bin/sha512sum"
ln -s "toybox_vendor" "/$vendor/bin/sleep"
ln -s "toybox_vendor" "/$vendor/bin/sort"
ln -s "toybox_vendor" "/$vendor/bin/split"
ln -s "toybox_vendor" "/$vendor/bin/start"
ln -s "toybox_vendor" "/$vendor/bin/stat"
ln -s "toybox_vendor" "/$vendor/bin/stop"
ln -s "toybox_vendor" "/$vendor/bin/strings"
ln -s "toybox_vendor" "/$vendor/bin/stty"
ln -s "toybox_vendor" "/$vendor/bin/swapoff"
ln -s "toybox_vendor" "/$vendor/bin/swapon"
ln -s "toybox_vendor" "/$vendor/bin/sync"
ln -s "toybox_vendor" "/$vendor/bin/sysctl"
ln -s "toybox_vendor" "/$vendor/bin/tac"
ln -s "toybox_vendor" "/$vendor/bin/tail"
ln -s "toybox_vendor" "/$vendor/bin/tar"
ln -s "toybox_vendor" "/$vendor/bin/taskset"
ln -s "toybox_vendor" "/$vendor/bin/tee"
ln -s "toybox_vendor" "/$vendor/bin/time"
ln -s "toybox_vendor" "/$vendor/bin/timeout"
ln -s "toybox_vendor" "/$vendor/bin/top"
ln -s "toybox_vendor" "/$vendor/bin/touch"
ln -s "toybox_vendor" "/$vendor/bin/tr"
ln -s "toybox_vendor" "/$vendor/bin/traceroute"
ln -s "toybox_vendor" "/$vendor/bin/traceroute6"
ln -s "toybox_vendor" "/$vendor/bin/true"
ln -s "toybox_vendor" "/$vendor/bin/truncate"
ln -s "toybox_vendor" "/$vendor/bin/tty"
ln -s "toybox_vendor" "/$vendor/bin/tunctl"
ln -s "toybox_vendor" "/$vendor/bin/ulimit"
ln -s "toybox_vendor" "/$vendor/bin/umount"
ln -s "toybox_vendor" "/$vendor/bin/uname"
ln -s "toybox_vendor" "/$vendor/bin/uniq"
ln -s "toybox_vendor" "/$vendor/bin/unix2dos"
ln -s "toybox_vendor" "/$vendor/bin/uptime"
ln -s "toybox_vendor" "/$vendor/bin/usleep"
ln -s "toybox_vendor" "/$vendor/bin/uudecode"
ln -s "toybox_vendor" "/$vendor/bin/uuencode"
ln -s "toybox_vendor" "/$vendor/bin/vconfig"
ln -s "toybox_vendor" "/$vendor/bin/vmstat"
ln -s "toybox_vendor" "/$vendor/bin/wc"
ln -s "toybox_vendor" "/$vendor/bin/which"
ln -s "toybox_vendor" "/$vendor/bin/whoami"
ln -s "toybox_vendor" "/$vendor/bin/xargs"
ln -s "toybox_vendor" "/$vendor/bin/xxd"
ln -s "toybox_vendor" "/$vendor/bin/yes"
ln -s "toybox_vendor" "/$vendor/bin/zcat"

chcon -h u:object_r:vendor_toolbox_exec:s0 "/$vendor/bin/toybox_vendor"
